title: Harper Priebe
description: Helena Priebe
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
